### ISSUE TITLE
Why compose and kubernetes?

### ISSUE THREAD

**Issue by mikecann** [markhilton/larakube#1]
Hi,

I have been studying this repo and was wondering why you have both compose and kubernetes together in here? 

If its just for local dev purposes wouldnt it make sense to do local development within the kubernetes so you are as close to prod's environment as you can get?

Cheers.

**Comment by HSkogmo** [comment]
Hi @mikecann,

I've also been studying this repo and k8s lately, and thanks a lot @markhilton for putting this together. It has proven immensely useful for me in learning how to host PHP applications, using private registries, and the magical cloud vendor integration that just spawns AWS Elastic Load Balancers.

From what I've heard it's sometimes beneficial to run compose in development due to it being easier to debug and to have the shared drive between the local machine and the compose containers. Then you don't have to rebuild your containers every time you perform a code change. Perhaps there's a k8s native solution, but maybe it's cumbersome.

You can hear Amit Bezalel chime in on this on the AWS Tel Aviv Summit 2018 talk "Kubernetes on AWS". Here's a link with timecode to the relevant section: https://youtu.be/mfx7whOKUH0?t=16m7s

Hope that helps!

**Comment by mikecann** [comment]
@HSkogmo Awesome! That was pretty much the same conclusion that I came to too but I wanted to hear it from the horses mouth so to speak.

Thanks for the link too, will give it a watch soon! :smile:
